<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['pagination']['full_tag_open'] = '<div class="pagination"><ul>';
$config['pagination']['full_tag_close'] = '<ul></div>';
$config['pagination']['first_link'] = 'First';
$config['pagination']['first_tag_open'] = '<li>';
$config['pagination']['first_tag_close'] = '</li>';        
$config['pagination']['last_link'] = 'Last';
$config['pagination']['last_tag_open'] = '<li>';
$config['pagination']['last_tag_close'] = '</li>';
$config['pagination']['next_link'] = 'Next &rarr;';
$config['pagination']['next_tag_open'] = '<li class="next">';
$config['pagination']['next_tag_close'] = '</li>';
$config['pagination']['prev_link'] = '&larr; Previous';
$config['pagination']['prev_tag_open'] = '<li class="prev">';
$config['pagination']['prev_tag_close'] = '</li>';
$config['pagination']['cur_tag_open'] = '<li class="active"><a href="#">';
$config['pagination']['cur_tag_close'] = '</a></li>';
$config['pagination']['num_tag_open'] = '<li>';
$config['pagination']['num_tag_close'] = '</li>';   